apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-agent
  namespace: logging-hw
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: log-agent-role
  namespace: logging-hw
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: log-agent-binding
  namespace: logging-hw
subjects:
  - kind: ServiceAccount
    name: log-agent
    namespace: logging-hw
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: log-agent-role